# CSE 5243 - Introduction to Data Mining
## Homework 5: Associations
- Semester: Autumn 2020
- Instructor: Tom Bihari
- Section: Tuesday/Thursday 9:35AM
- Student Name: Bianca Dizon
- Student Email: dizon.11@osu.edu
- Student ID: 500126259

In [63]:
# import libraries
import sys
# !{sys.executable} -m pip install mlxtend
!pip install mlxtend
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth
from mlxtend.frequent_patterns import association_rules

Requirement already satisfied: mlxtend in c:\users\bianca dizon\anaconda3\lib\site-packages (0.18.0)
Requirement already satisfied: numpy>=1.16.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.19.2)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (0.23.2)
Requirement already satisfied: pandas>=0.24.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.1.3)
Requirement already satisfied: joblib>=0.13.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (0.17.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scipy>=1.2.1 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: setuptools in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (50.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\bianca dizon\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\bianca dizon\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.19.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\bianca dizon\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\bianca dizon\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: six in c:\users\bianca dizon\appdata\roaming\python\python38\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\bianca dizon\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.19.2)
Requirement already satisfied: pytz>=2017.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: six in c:\users\bianca dizon\appdata\roaming\python\python38\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: joblib>=0.13.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (0.17.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\bianca dizon\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)
Requirement already satisfied: numpy>=1.16.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.19.2)
Requirement already satisfied: numpy>=1.16.2 in c:\users\bianca dizon\anaconda3\lib\site-packages (from mlxtend) (1.19.2)

## Preprocess Data

In [59]:
# 1A) find the number of datasets

# read in excel sheet
# records_df = pd.read_excel('CSE5243 Au20 Bihari HW5 DizonBianca.xlsx', sheet_name='Data-Records')
df = pd.read_excel('CSE5243 Au20 Bihari HW5 DizonBianca.xlsx', sheet_name='Data-Table')
# print(df)

items_df = df.iloc[:, 1:7]
print(items_df.shape)
items_list = items_df.values.tolist()
# print(items_list[0][3])
# print(items_list[0])
# print(len(items_list[0]))
items = []
for i in range(len(items_df)):
    row = []
#     for j in range(len(items_list[i])):
    if items_list[i][0] == 1:
        row.append("Apples")
    if items_list[i][1] == 1:
        row.append("Bananas")
    if items_list[i][2] == 1:
        row.append("Carrots")
    if items_list[i][3] == 1:
        row.append("Donuts")
    if items_list[i][4] == 1:
        row.append("Eggs")
    if items_list[i][5] == 1:
        row.append("Fish")
    items.append(row)
print(items)

(50, 6)
[['Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs'], ['Donuts'], ['Apples', 'Donuts', 'Fish'], ['Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs'], ['Bananas', 'Carrots'], ['Donuts'], ['Bananas'], ['Donuts', 'Eggs'], ['Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs', 'Fish'], ['Donuts'], ['Apples', 'Carrots', 'Donuts', 'Fish'], ['Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Donuts'], ['Apples', 'Bananas'], ['Donuts', 'Eggs'], ['Bananas', 'Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs', 'Fish'], ['Donuts'], ['Apples', 'Donuts', 'Fish'], ['Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Eggs'], ['Bananas', 'Carrots'], ['Apples', 'Donuts'], ['Bananas'], ['Donuts', 'Eggs'], ['Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Eggs', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Donuts', 'Eggs', 'Fish']]

## Calculate Basic Statistics

In [39]:
# number of itemset created from a universe of six items
num_itemsets = 2**len(items_list[0])
print(num_itemsets)
# number of rules that could be created from a universe of six items
num_rules = (3**len(items_list[0])) - (2**(len(items_list[0])+1)) + 1
print(num_rules)

64
602

## Generate the Frequent Itemsets

In [40]:
# number of itemsets in data
print("number of itemsets in data:", len(items))

# number of frequent itemsets for MinSup=2
# print all frequent itemsets
def freq_itemsets(items, minsup):
    num = 0
    for i in range(len(items)):
        if len(items[i]) >= minsup:
            print(items[i], end=", ")
            num += 1
    print()
    print("number of frequent itemsets minsup=", minsup, ": ", num)

freq_itemsets(items, 2)
print()
freq_itemsets(items, 3)
print()
freq_itemsets(items, 4)

number of itemsets in data: 50
['Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs'], ['Apples', 'Donuts', 'Fish'], ['Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs'], ['Bananas', 'Carrots'], ['Donuts', 'Eggs'], ['Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs', 'Fish'], ['Apples', 'Carrots', 'Donuts', 'Fish'], ['Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Apples', 'Bananas'], ['Donuts', 'Eggs'], ['Bananas', 'Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs', 'Fish'], ['Apples', 'Donuts', 'Fish'], ['Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Eggs'], ['Bananas', 'Carrots'], ['Apples', 'Donuts'], ['Donuts', 'Eggs'], ['Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Eggs', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Donuts', 'Eggs', 'Fish'],
number of frequent itemsets minsup= 2 :  43

['Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Apples', 'Donuts', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs', 'Fish'], ['Apples', 'Carrots', 'Donuts', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Bananas', 'Eggs', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Bananas', 'Donuts', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Donuts'], ['Carrots', 'Eggs', 'Fish'], ['Apples', 'Donuts', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Eggs'], ['Bananas', 'Carrots', 'Fish'], ['Bananas', 'Carrots', 'Eggs'], ['Apples', 'Bananas', 'Carrots', 'Eggs', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Donuts', 'Eggs', 'Fish'],
number of frequent itemsets minsup= 3 :  26

['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Carrots', 'Donuts', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Eggs', 'Fish'], ['Apples', 'Bananas', 'Carrots', 'Donuts', 'Eggs', 'Fish'],
number of frequent itemsets minsup= 4 :  9

In [50]:
# prune itemsets APRIORI
frequent_itemsets = apriori(items_df, min_support=0.03, use_colnames=True)
print(frequent_itemsets)
# print(len(items)- frequent_itemsets.shape[0])
pruned_set = []
for i in range(len(items)):
    item_set = set()
    for j in range(len(items[i])):
        item_set.add(items[i][j])
#     print(items[i])
#     print(item_set)
    if frequent_itemsets[ frequent_itemsets['itemsets'] == item_set].empty == True:
#         print("y")
#         print(item_set)
        pruned_set.append(item_set)
print(pruned_set)
print("pruned itemsets:")
list(set([ tuple(set(i)) for i in pruned_set]))
print(len(pruned_set))

    support                                itemsets
0      0.34                                (Apples)
1      0.58                               (Bananas)
2      0.48                               (Carrots)
3      0.40                                (Donuts)
4      0.40                                  (Eggs)
5      0.42                                  (Fish)
6      0.26                       (Apples, Bananas)
7      0.18                       (Apples, Carrots)
8      0.16                        (Apples, Donuts)
9      0.06                          (Apples, Eggs)
10     0.22                          (Apples, Fish)
11     0.34                      (Carrots, Bananas)
12     0.10                       (Bananas, Donuts)
13     0.22                         (Bananas, Eggs)
14     0.26                         (Fish, Bananas)
15     0.04                       (Carrots, Donuts)
16     0.16                         (Carrots, Eggs)
17     0.36                         (Carrots, Fish)
18     0.16                          (Eggs, Donuts)
19     0.08                          (Fish, Donuts)
20     0.10                            (Fish, Eggs)
21     0.16              (Apples, Carrots, Bananas)
22     0.08               (Apples, Bananas, Donuts)
23     0.06                 (Apples, Bananas, Eggs)
24     0.16                 (Apples, Fish, Bananas)
25     0.04               (Apples, Carrots, Donuts)
26     0.04                 (Apples, Carrots, Eggs)
27     0.18                 (Apples, Carrots, Fish)
28     0.08                  (Apples, Fish, Donuts)
29     0.04                    (Apples, Fish, Eggs)
30     0.10                (Carrots, Bananas, Eggs)
31     0.24                (Carrots, Fish, Bananas)
32     0.04                 (Eggs, Bananas, Donuts)
33     0.06                   (Fish, Bananas, Eggs)
34     0.04                 (Carrots, Fish, Donuts)
35     0.08                   (Carrots, Fish, Eggs)
36     0.04        (Apples, Carrots, Bananas, Eggs)
37     0.16        (Apples, Carrots, Fish, Bananas)
38     0.04           (Apples, Fish, Bananas, Eggs)
39     0.04         (Apples, Carrots, Fish, Donuts)
40     0.04           (Apples, Carrots, Fish, Eggs)
41     0.04          (Carrots, Fish, Bananas, Eggs)
42     0.04  (Apples, Bananas, Fish, Eggs, Carrots)
[{'Apples', 'Bananas', 'Fish', 'Eggs', 'Donuts', 'Carrots'}]
pruned itemsets:
1

In [53]:
max_frequent = fpmax(items_df, min_support=0.03, use_colnames=True)
print(max_frequent)
pruned_set = []
for i in range(len(items)):
    item_set = set()
    for j in range(len(items[i])):
        item_set.add(items[i][j])
#     print(items[i])
#     print(item_set)
    if max_frequent[ max_frequent['itemsets'] == item_set].empty == True:
#         print("y")
#         print(item_set)
        pruned_set.append(item_set)
print(pruned_set)
print("pruned itemsets:")
list(set([ tuple(set(i)) for i in pruned_set]))
print(len(pruned_set))

   support                                itemsets
0     0.04  (Apples, Bananas, Fish, Eggs, Carrots)
1     0.04         (Apples, Carrots, Fish, Donuts)
2     0.08               (Apples, Bananas, Donuts)
3     0.04                 (Eggs, Bananas, Donuts)
[{'Eggs', 'Donuts'}, {'Carrots', 'Fish', 'Bananas'}, {'Bananas', 'Eggs'}, {'Apples', 'Carrots', 'Fish', 'Bananas'}, {'Carrots', 'Eggs'}, {'Donuts'}, {'Apples', 'Fish', 'Donuts'}, {'Carrots', 'Fish'}, {'Apples', 'Carrots', 'Fish', 'Bananas'}, {'Bananas', 'Eggs'}, {'Carrots', 'Bananas'}, {'Donuts'}, {'Bananas'}, {'Eggs', 'Donuts'}, {'Eggs', 'Donuts'}, {'Carrots', 'Fish', 'Bananas'}, {'Carrots', 'Bananas', 'Eggs'}, {'Apples', 'Carrots', 'Fish', 'Bananas'}, {'Carrots', 'Fish', 'Eggs'}, {'Donuts'}, {'Carrots', 'Fish'}, {'Apples', 'Carrots', 'Fish', 'Bananas'}, {'Fish', 'Bananas', 'Eggs'}, {'Carrots', 'Bananas', 'Eggs'}, {'Donuts'}, {'Apples', 'Bananas'}, {'Eggs', 'Donuts'}, {'Carrots', 'Fish', 'Bananas'}, {'Bananas', 'Eggs'}, {'Apples', 'Carrots', 'Fish', 'Bananas'}, {'Carrots', 'Fish', 'Eggs'}, {'Donuts'}, {'Apples', 'Fish', 'Donuts'}, {'Carrots', 'Fish'}, {'Apples', 'Carrots', 'Fish', 'Bananas'}, {'Apples', 'Bananas', 'Eggs'}, {'Carrots', 'Bananas'}, {'Apples', 'Donuts'}, {'Bananas'}, {'Eggs', 'Donuts'}, {'Eggs', 'Donuts'}, {'Carrots', 'Fish', 'Bananas'}, {'Carrots', 'Bananas', 'Eggs'}, {'Apples', 'Bananas', 'Fish', 'Eggs', 'Donuts', 'Carrots'}]
pruned itemsets:
44

In [61]:
# CLOSED ITEMSETS
all_itemsets = apriori(items_df, min_support=0.000001, use_colnames=True)
# print(all_itemsets)
su = all_itemsets.support.unique()#all unique support count
#Dictionay storing itemset with same support count key
fredic = {}
for i in range(len(su)):
    inset = list(all_itemsets.loc[all_itemsets.support ==su[i]]['itemsets'])
    fredic[su[i]] = inset
#Dictionay storing itemset with  support count <= key
fredic2 = {}
for i in range(len(su)):
    inset2 = list(all_itemsets.loc[all_itemsets.support<=su[i]]['itemsets'])
    fredic2[su[i]] = inset2
#Find Closed frequent itemset
# start_time = time.time()
cl = []
for index, row in all_itemsets.iterrows():
    isclose = True
    cli = row['itemsets']
    cls = row['support']
    checkset = fredic[cls]
    for i in checkset:
        if (cli!=i):
            if(frozenset.issubset(cli,i)):
                isclose = False
                break
    
    if(isclose):
        cl.append(row['itemsets'])
print(len(cl))
print(cl)

30
[frozenset({'Apples'}), frozenset({'Bananas'}), frozenset({'Carrots'}), frozenset({'Donuts'}), frozenset({'Eggs'}), frozenset({'Fish'}), frozenset({'Apples', 'Bananas'}), frozenset({'Apples', 'Donuts'}), frozenset({'Apples', 'Fish'}), frozenset({'Carrots', 'Bananas'}), frozenset({'Bananas', 'Donuts'}), frozenset({'Bananas', 'Eggs'}), frozenset({'Fish', 'Bananas'}), frozenset({'Carrots', 'Eggs'}), frozenset({'Carrots', 'Fish'}), frozenset({'Eggs', 'Donuts'}), frozenset({'Fish', 'Eggs'}), frozenset({'Apples', 'Bananas', 'Donuts'}), frozenset({'Apples', 'Bananas', 'Eggs'}), frozenset({'Apples', 'Carrots', 'Fish'}), frozenset({'Apples', 'Fish', 'Donuts'}), frozenset({'Carrots', 'Bananas', 'Eggs'}), frozenset({'Carrots', 'Fish', 'Bananas'}), frozenset({'Eggs', 'Bananas', 'Donuts'}), frozenset({'Fish', 'Bananas', 'Eggs'}), frozenset({'Carrots', 'Fish', 'Eggs'}), frozenset({'Apples', 'Carrots', 'Fish', 'Bananas'}), frozenset({'Apples', 'Carrots', 'Fish', 'Donuts'}), frozenset({'Apples', 'Bananas', 'Fish', 'Eggs', 'Carrots'}), frozenset({'Apples', 'Bananas', 'Fish', 'Eggs', 'Donuts', 'Carrots'})]

In [56]:
##minsup=3 CLOSED ITEMSETS
su = frequent_itemsets.support.unique()#all unique support count
#Dictionay storing itemset with same support count key
fredic = {}
for i in range(len(su)):
    inset = list(frequent_itemsets.loc[frequent_itemsets.support ==su[i]]['itemsets'])
    fredic[su[i]] = inset
#Dictionay storing itemset with  support count <= key
fredic2 = {}
for i in range(len(su)):
    inset2 = list(frequent_itemsets.loc[frequent_itemsets.support<=su[i]]['itemsets'])
    fredic2[su[i]] = inset2
#Find Closed frequent itemset
# start_time = time.time()
cl = []
for index, row in frequent_itemsets.iterrows():
    isclose = True
    cli = row['itemsets']
    cls = row['support']
    checkset = fredic[cls]
    for i in checkset:
        if (cli!=i):
            if(frozenset.issubset(cli,i)):
                isclose = False
                break
    
    if(isclose):
        cl.append(row['itemsets'])
print(len(cl))
print(cl)

29
[frozenset({'Apples'}), frozenset({'Bananas'}), frozenset({'Carrots'}), frozenset({'Donuts'}), frozenset({'Eggs'}), frozenset({'Fish'}), frozenset({'Apples', 'Bananas'}), frozenset({'Apples', 'Donuts'}), frozenset({'Apples', 'Fish'}), frozenset({'Carrots', 'Bananas'}), frozenset({'Bananas', 'Donuts'}), frozenset({'Bananas', 'Eggs'}), frozenset({'Fish', 'Bananas'}), frozenset({'Carrots', 'Eggs'}), frozenset({'Carrots', 'Fish'}), frozenset({'Eggs', 'Donuts'}), frozenset({'Fish', 'Eggs'}), frozenset({'Apples', 'Bananas', 'Donuts'}), frozenset({'Apples', 'Bananas', 'Eggs'}), frozenset({'Apples', 'Carrots', 'Fish'}), frozenset({'Apples', 'Fish', 'Donuts'}), frozenset({'Carrots', 'Bananas', 'Eggs'}), frozenset({'Carrots', 'Fish', 'Bananas'}), frozenset({'Eggs', 'Bananas', 'Donuts'}), frozenset({'Fish', 'Bananas', 'Eggs'}), frozenset({'Carrots', 'Fish', 'Eggs'}), frozenset({'Apples', 'Carrots', 'Fish', 'Bananas'}), frozenset({'Apples', 'Carrots', 'Fish', 'Donuts'}), frozenset({'Apples', 'Bananas', 'Fish', 'Eggs', 'Carrots'})]

## Generate Rules

In [67]:
# get potential number of rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0)
print(rules)
print("potential number of rules:",len(rules))

    antecedents                       consequents  antecedent support  \
0      (Apples)                         (Bananas)                0.34
1     (Bananas)                          (Apples)                0.58
2      (Apples)                         (Carrots)                0.34
3     (Carrots)                          (Apples)                0.48
4      (Apples)                          (Donuts)                0.34
..          ...                               ...                 ...
229    (Apples)    (Carrots, Fish, Bananas, Eggs)                0.34
230   (Bananas)     (Apples, Carrots, Fish, Eggs)                0.58
231      (Fish)  (Apples, Carrots, Bananas, Eggs)                0.42
232      (Eggs)  (Apples, Carrots, Fish, Bananas)                0.40
233   (Carrots)     (Apples, Fish, Bananas, Eggs)                0.48

     consequent support  support  confidence      lift  leverage  conviction
0                  0.58     0.26    0.764706  1.318458    0.0628    1.785000
1                  0.34     0.26    0.448276  1.318458    0.0628    1.196250
2                  0.48     0.18    0.529412  1.102941    0.0168    1.105000
3                  0.34     0.18    0.375000  1.102941    0.0168    1.056000
4                  0.40     0.16    0.470588  1.176471    0.0240    1.133333
..                  ...      ...         ...       ...       ...         ...
229                0.04     0.04    0.117647  2.941176    0.0264    1.088000
230                0.04     0.04    0.068966  1.724138    0.0168    1.031111
231                0.04     0.04    0.095238  2.380952    0.0232    1.061053
232                0.16     0.04    0.100000  0.625000   -0.0240    0.933333
233                0.04     0.04    0.083333  2.083333    0.0208    1.047273

[234 rows x 9 columns]
potential number of rules: 234

In [86]:
print("number of rules that could be created from {B,C,F}:", len(rules[rules['antecedents'] == {'Bananas', 'Carrots', 'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas', 'Carrots', 'Fish'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {B,C}:", len(rules[rules['antecedents'] == {'Bananas', 'Carrots'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas', 'Carrots'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {C,F}:", len(rules[rules['antecedents'] == {'Carrots', 'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Carrots', 'Fish'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {B,F}:", len(rules[rules['antecedents'] == {'Bananas', 'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas','Fish'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {B}:", len(rules[rules['antecedents'] == {'Bananas'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {C}:", len(rules[rules['antecedents'] == {'Carrots'}]))
bcf_rules = rules[rules['antecedents'] == {'Carrots'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {F}:", len(rules[rules['antecedents'] == {'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Fish'}]
print(bcf_rules['consequents'])

# bcf_rules = rules[rules['antecedents'] == {'Bananas', 'Carrots', 'Fish'}]
# print(bcf_rules)
# print(bcf_rules['consequents'])

number of rules that could be created from {B,C,F}: 3
137          (Apples)
190            (Eggs)
216    (Apples, Eggs)
Name: consequents, dtype: object
number of rules that could be created from {B,C}: 7
32                 (Apples)
84                   (Eggs)
91                   (Fish)
127          (Apples, Eggs)
142          (Apples, Fish)
195            (Fish, Eggs)
225    (Apples, Fish, Eggs)
Name: consequents, dtype: object
number of rules that could be created from {C,F}: 9
68                    (Apples)
90                   (Bananas)
108                   (Donuts)
114                     (Eggs)
141          (Apples, Bananas)
169           (Apples, Donuts)
183             (Apples, Eggs)
194            (Bananas, Eggs)
227    (Apples, Bananas, Eggs)
Name: consequents, dtype: object
number of rules that could be created from {B,F}: 7
50                    (Apples)
92                   (Carrots)
102                     (Eggs)
143          (Apples, Carrots)
155             (Apples, Eggs)
197            (Carrots, Eggs)
223    (Apples, Carrots, Eggs)
Name: consequents, dtype: object
number of rules that could be created from {B}: 18
1                           (Apples)
11                         (Carrots)
12                          (Donuts)
14                            (Eggs)
17                            (Fish)
35                 (Apples, Carrots)
40                  (Apples, Donuts)
46                    (Apples, Eggs)
53                    (Apples, Fish)
88                   (Carrots, Eggs)
95                   (Carrots, Fish)
100                   (Donuts, Eggs)
106                     (Fish, Eggs)
132          (Apples, Carrots, Eggs)
147          (Apples, Carrots, Fish)
160             (Apples, Fish, Eggs)
202            (Carrots, Fish, Eggs)
230    (Apples, Carrots, Fish, Eggs)
Name: consequents, dtype: object
number of rules that could be created from {C}: 19
3                           (Apples)
10                         (Bananas)
18                          (Donuts)
20                            (Eggs)
22                            (Fish)
34                 (Apples, Bananas)
58                  (Apples, Donuts)
64                    (Apples, Eggs)
70                    (Apples, Fish)
87                   (Bananas, Eggs)
93                   (Fish, Bananas)
111                   (Fish, Donuts)
117                     (Fish, Eggs)
131          (Apples, Bananas, Eggs)
145          (Apples, Fish, Bananas)
173           (Apples, Fish, Donuts)
187             (Apples, Fish, Eggs)
200            (Fish, Bananas, Eggs)
233    (Apples, Fish, Bananas, Eggs)
Name: consequents, dtype: object
number of rules that could be created from {F}: 19
9                              (Apples)
16                            (Bananas)
23                            (Carrots)
26                             (Donuts)
28                               (Eggs)
52                    (Apples, Bananas)
71                    (Apples, Carrots)
76                     (Apples, Donuts)
82                       (Apples, Eggs)
94                   (Carrots, Bananas)
105                     (Bananas, Eggs)
112                   (Carrots, Donuts)
118                     (Carrots, Eggs)
146          (Apples, Carrots, Bananas)
159             (Apples, Bananas, Eggs)
174           (Apples, Carrots, Donuts)
188             (Apples, Carrots, Eggs)
201            (Carrots, Bananas, Eggs)
231    (Apples, Carrots, Bananas, Eggs)
Name: consequents, dtype: object

In [100]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequents_len
0,(Apples),(Bananas),0.34,0.58,0.26,0.764706,1.318458,0.0628,1.785000,1,1
1,(Bananas),(Apples),0.58,0.34,0.26,0.448276,1.318458,0.0628,1.196250,1,1
2,(Apples),(Carrots),0.34,0.48,0.18,0.529412,1.102941,0.0168,1.105000,1,1
3,(Carrots),(Apples),0.48,0.34,0.18,0.375000,1.102941,0.0168,1.056000,1,1
4,(Apples),(Donuts),0.34,0.40,0.16,0.470588,1.176471,0.0240,1.133333,1,1
...,...,...,...,...,...,...,...,...,...,...,...
229,(Apples),"(Carrots, Fish, Bananas, Eggs)",0.34,0.04,0.04,0.117647,2.941176,0.0264,1.088000,1,4
230,(Bananas),"(Apples, Carrots, Fish, Eggs)",0.58,0.04,0.04,0.068966,1.724138,0.0168,1.031111,1,4
231,(Fish),"(Apples, Carrots, Bananas, Eggs)",0.42,0.04,0.04,0.095238,2.380952,0.0232,1.061053,1,4
232,(Eggs),"(Apples, Carrots, Fish, Bananas)",0.40,0.16,0.04,0.100000,0.625000,-0.0240,0.933333,1,4
233,(Carrots),"(Apples, Fish, Bananas, Eggs)",0.48,0.04,0.04,0.083333,2.083333,0.0208,1.047273,1,4

In [106]:
rules = rules[(rules['confidence'] >= 0.75)]
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequents_len
0,(Apples),(Bananas),0.34,0.58,0.26,0.764706,1.318458,0.0628,1.785,1,1
22,(Carrots),(Fish),0.48,0.42,0.36,0.750000,1.785714,0.1584,2.320,1,1
23,(Fish),(Carrots),0.42,0.48,0.36,0.857143,1.785714,0.1584,3.640,1,1
30,"(Apples, Carrots)",(Bananas),0.18,0.58,0.16,0.888889,1.532567,0.0556,3.780,2,1
38,"(Bananas, Donuts)",(Apples),0.10,0.34,0.08,0.800000,2.352941,0.0460,3.300,2,1
43,"(Apples, Eggs)",(Bananas),0.06,0.58,0.06,1.000000,1.724138,0.0252,inf,2,1
56,"(Carrots, Donuts)",(Apples),0.04,0.34,0.04,1.000000,2.941176,0.0264,inf,2,1
66,"(Apples, Carrots)",(Fish),0.18,0.42,0.18,1.000000,2.380952,0.1044,inf,2,1
67,"(Apples, Fish)",(Carrots),0.22,0.48,0.18,0.818182,1.704545,0.0744,2.860,2,1
74,"(Fish, Donuts)",(Apples),0.08,0.34,0.08,1.000000,2.941176,0.0528,inf,2,1
92,"(Fish, Bananas)",(Carrots),0.26,0.48,0.24,0.923077,1.923077,0.1152,6.760,2,1
109,"(Carrots, Donuts)",(Fish),0.04,0.42,0.04,1.000000,2.380952,0.0232,inf,2,1
116,"(Fish, Eggs)",(Carrots),0.10,0.48,0.08,0.800000,1.666667,0.0320,2.600,2,1
121,"(Apples, Carrots, Eggs)",(Bananas),0.04,0.58,0.04,1.000000,1.724138,0.0168,inf,3,1
134,"(Apples, Carrots, Fish)",(Bananas),0.18,0.58,0.16,0.888889,1.532567,0.0556,3.780,3,1
135,"(Apples, Carrots, Bananas)",(Fish),0.16,0.42,0.16,1.000000,2.380952,0.0928,inf,3,1
136,"(Apples, Fish, Bananas)",(Carrots),0.16,0.48,0.16,1.000000,2.083333,0.0832,inf,3,1
138,"(Apples, Carrots)","(Fish, Bananas)",0.18,0.26,0.16,0.888889,3.418803,0.1132,6.660,2,2
149,"(Apples, Fish, Eggs)",(Bananas),0.04,0.58,0.04,1.000000,1.724138,0.0168,inf,3,1
163,"(Apples, Carrots, Donuts)",(Fish),0.04,0.42,0.04,1.000000,2.380952,0.0232,inf,3,1
165,"(Carrots, Fish, Donuts)",(Apples),0.04,0.34,0.04,1.000000,2.941176,0.0264,inf,3,1
170,"(Carrots, Donuts)","(Apples, Fish)",0.04,0.22,0.04,1.000000,4.545455,0.0312,inf,2,2
177,"(Apples, Carrots, Eggs)",(Fish),0.04,0.42,0.04,1.000000,2.380952,0.0232,inf,3,1
178,"(Apples, Fish, Eggs)",(Carrots),0.04,0.48,0.04,1.000000,2.083333,0.0208,inf,3,1
204,"(Apples, Fish, Bananas, Eggs)",(Carrots),0.04,0.48,0.04,1.000000,2.083333,0.0208,inf,4,1
206,"(Apples, Carrots, Bananas, Eggs)",(Fish),0.04,0.42,0.04,1.000000,2.380952,0.0232,inf,4,1
207,"(Apples, Carrots, Fish, Eggs)",(Bananas),0.04,0.58,0.04,1.000000,1.724138,0.0168,inf,4,1
208,"(Carrots, Fish, Bananas, Eggs)",(Apples),0.04,0.34,0.04,1.000000,2.941176,0.0264,inf,4,1
212,"(Apples, Fish, Eggs)","(Carrots, Bananas)",0.04,0.34,0.04,1.000000,2.941176,0.0264,inf,3,2
214,"(Apples, Carrots, Eggs)","(Fish, Bananas)",0.04,0.26,0.04,1.000000,3.846154,0.0296,inf,3,2

In [107]:
print("number of rules that could be created from {B,C,F}:", len(rules[rules['antecedents'] == {'Bananas', 'Carrots', 'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas', 'Carrots', 'Fish'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {B,C}:", len(rules[rules['antecedents'] == {'Bananas', 'Carrots'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas', 'Carrots'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {C,F}:", len(rules[rules['antecedents'] == {'Carrots', 'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Carrots', 'Fish'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {B,F}:", len(rules[rules['antecedents'] == {'Bananas', 'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas','Fish'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {B}:", len(rules[rules['antecedents'] == {'Bananas'}]))
bcf_rules = rules[rules['antecedents'] == {'Bananas'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {C}:", len(rules[rules['antecedents'] == {'Carrots'}]))
bcf_rules = rules[rules['antecedents'] == {'Carrots'}]
print(bcf_rules['consequents'])
print("number of rules that could be created from {F}:", len(rules[rules['antecedents'] == {'Fish'}]))
bcf_rules = rules[rules['antecedents'] == {'Fish'}]
print(bcf_rules['consequents'])

number of rules that could be created from {B,C,F}: 0
Series([], Name: consequents, dtype: object)
number of rules that could be created from {B,C}: 0
Series([], Name: consequents, dtype: object)
number of rules that could be created from {C,F}: 0
Series([], Name: consequents, dtype: object)
number of rules that could be created from {B,F}: 1
92    (Carrots)
Name: consequents, dtype: object
number of rules that could be created from {B}: 0
Series([], Name: consequents, dtype: object)
number of rules that could be created from {C}: 1
22    (Fish)
Name: consequents, dtype: object
number of rules that could be created from {F}: 1
23    (Carrots)
Name: consequents, dtype: object

In [116]:
# get potential number of rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0)
rules = rules[(rules['lift'] > 1)]
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Apples),(Bananas),0.34,0.58,0.26,0.764706,1.318458,0.0628,1.785000
1,(Bananas),(Apples),0.58,0.34,0.26,0.448276,1.318458,0.0628,1.196250
2,(Apples),(Carrots),0.34,0.48,0.18,0.529412,1.102941,0.0168,1.105000
3,(Carrots),(Apples),0.48,0.34,0.18,0.375000,1.102941,0.0168,1.056000
4,(Apples),(Donuts),0.34,0.40,0.16,0.470588,1.176471,0.0240,1.133333
...,...,...,...,...,...,...,...,...,...
228,"(Carrots, Eggs)","(Apples, Fish, Bananas)",0.16,0.16,0.04,0.250000,1.562500,0.0144,1.120000
229,(Apples),"(Carrots, Fish, Bananas, Eggs)",0.34,0.04,0.04,0.117647,2.941176,0.0264,1.088000
230,(Bananas),"(Apples, Carrots, Fish, Eggs)",0.58,0.04,0.04,0.068966,1.724138,0.0168,1.031111
231,(Fish),"(Apples, Carrots, Bananas, Eggs)",0.42,0.04,0.04,0.095238,2.380952,0.0232,1.061053
233,(Carrots),"(Apples, Fish, Bananas, Eggs)",0.48,0.04,0.04,0.083333,2.083333,0.0208,1.047273

In [135]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0)
rules = rules[(rules['lift'] < 1)]
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(Apples),(Eggs),0.34,0.40,0.06,0.176471,0.441176,-0.0760,0.728571
7,(Eggs),(Apples),0.40,0.34,0.06,0.150000,0.441176,-0.0760,0.776471
12,(Bananas),(Donuts),0.58,0.40,0.10,0.172414,0.431034,-0.1320,0.725000
13,(Donuts),(Bananas),0.40,0.58,0.10,0.250000,0.431034,-0.1320,0.560000
14,(Bananas),(Eggs),0.58,0.40,0.22,0.379310,0.948276,-0.0120,0.966667
...,...,...,...,...,...,...,...,...,...
201,(Fish),"(Carrots, Bananas, Eggs)",0.42,0.10,0.04,0.095238,0.952381,-0.0020,0.994737
202,(Bananas),"(Carrots, Fish, Eggs)",0.58,0.08,0.04,0.068966,0.862069,-0.0064,0.988148
203,(Eggs),"(Carrots, Fish, Bananas)",0.40,0.24,0.04,0.100000,0.416667,-0.0560,0.844444
205,"(Apples, Carrots, Fish, Bananas)",(Eggs),0.16,0.40,0.04,0.250000,0.625000,-0.0240,0.800000
232,(Eggs),"(Apples, Carrots, Fish, Bananas)",0.40,0.16,0.04,0.100000,0.625000,-0.0240,0.933333

In [147]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0)
rules = rules[rules['antecedents'] == {'Bananas'}]
rules_list = rules['support']
rules_list = rules_list.values.tolist()
# print(max(rules_list))
# print(min(rules_list))
min_b = min(rules_list)
max_b =max(rules_list)
# print(min_b)
print(max_b)
rules =association_rules(frequent_itemsets, metric="lift", min_threshold=0)
rules = rules[rules['antecedents'] == {'Carrots'}]
rules_list = rules['support']
rules_list = rules_list.values.tolist()
# print(max(rules_list))
# print(min(rules_list))
min_c = min(rules_list)
max_c =max(rules_list)
# print(min_c)
print(max_c)
rules =association_rules(frequent_itemsets, metric="lift", min_threshold=0)
rules = rules[rules['antecedents'] == {'Fish'}]
rules_list = rules['support']
rules_list = rules_list.values.tolist()
# print(max(rules_list))
# print(min(rules_list))
min_f = min(rules_list)
max_f =max(rules_list)
# print(min_f)
print(max_f)
cross = min_f / max_f
print(cross)
# rules
# rules_list = rules['support']
# rules_list = rules_list.values.tolist()
# print(max(rules_list))
# print(min(rules_list))
# print(min(rules_list)/max(rules_list))

0.34
0.36
0.36
0.11111111111111112

In [148]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0)
rules = rules[rules['antecedents'] == {'Bananas', 'Carrots', 'Fish'}]
rules_list = rules['confidence']
rules_list = rules_list.values.tolist()
# print(max(rules_list))
print(min(rules_list))

0.16666666666666669